config/routes.rb
RailsTictactoe::Application.routes.draw do
  get "transaction/index"

  get "transaction/show"

  get "transaction/new"

  get "transaction/create"

  get "transaction/edit"

  get "transaction/update"

  get "transaction/destroy"

  get "account/index"

  get "account/show"

  get "account/new"

  get "account/create"

  get "account/edit"

  get "account/update"

  get "account/destroy"

  get "user/index"

  get "user/show"

  get "user/new"

  get "user/create"

  get "user/edit"

  get "user/update"

  get "user/destroy"

  root to: 'logins#new'
  resources :users
  resources :games, :except => [:new, :edit]
  resources :logins, :only => [:new, :create, :destroy]
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :board, :user_id, :won, :winner
  serialize :board
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :fname, :lname, :password, :password_confirmation, :uname
  
  has_many :games
  
  validates :fname, :presence => true
  validates :lname, :presence => true
  validates :uname, :uniqueness => true, :format => { :with => /^[a-zA-Z0-9_]+$/ }
  validates :email, :uniqueness => true, :format => { :with => /.+@.+\..+/i }

  def name
    fname + " " + lname
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  def authorize
    if current_user.nil?
      flash[:notice] = "Please log in before trying that."
      redirect_to :new_login
    end
  end
  
  private
  
  # Return either `nil` or a User object.
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    authorize
    @games = current_user.games.all
  end

  def show
    authorize
    @game = Game.find(params[:id])
  end

  def create
    authorize
    game = Game.create({:user_id => session[:user_id]})
    redirect_to(game_path(game.id))
  end

  def update
    authorize
    game = Game.find(params[:id])
    game.update_attributes(params[:game])
    redirect_to(games_path)
  end

  def destroy
    authorize
    game = Game.find(params[:id])
    game.delete
  end
end

app/controllers/gamess_controller.rb
class GamessController < ApplicationController
  def index
  end

  def show
  end

  def add
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root
    else
      flash[:notice] = "Invalid email address or password"
      redirect_to(:new_login)
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(:root)
  end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    authorize
    if current_user.id == params[:id]
      @user = User.find(params[:id])
    else
      flash[:notice] = "Cannot edit another person's profile."
      redirect_to(:root)
    end
  end

  def create
    user = User.new(params[:user])
    
    if user.save
      flash[:notice] = "Welcome #{user.fname}!"
      session[:user_id] = user.id # "auto-login"
      redirect_to(user_path(user.id))
    else
      render "new"
    end
  end

  def update
    authorize
    if current_user.id == params[:id]
      user = User.find(params[:id])
      user.update_attributes(params[:user])
      flash[:notice] = "Profile saved."
    else
      flash[:notice] = "Cannot update another person's profile."
      redirect_to(:root)
    end
    
    redirect_to(user_path(user.id))
  end

  def destroy
    authorize
    if current_user.id == params[:id]
      user = User.find(params[:id])
      user.delete
      session[:user_id] = nil
      flash[:notice] = "User #{user.uname} has beed deleted."
    else
      flash[:notice] = "Cannot delete another person's profile."
    end
    redirect_to(:root)
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gamess_helper.rb
module GamessHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1>Games</h1>

<% @games.each do |game| %>
  <p>
    <%= game.id %> <%= link_to(game.user.name, game_path(game.id)) %>
  </p>
<% end %>
<p>
  <%= link_to("New Game", games_path(current_user.id), :method=> :post) %>
</p>

app/views/games/show.html.erb
<div id="gameInfo">
  <h1>Tic Tac Toe</h1>
  <h5>Game <%= @game.id %></h5>
  
  <h3>Current Player: <span id="player">X</span></h3>
</div>
<div id="board">
  <h1 id="0" class="square"></h1>
  <h1 id="1" class="square"></h1>
  <h1 id="2" class="square"></h1>
  <h1 id="3" class="square"></h1>
  <h1 id="4" class="square"></h1>
  <h1 id="5" class="square"></h1>
  <h1 id="6" class="square"></h1>
  <h1 id="7" class="square"></h1>
  <h1 id="8" class="square"></h1>
</div>

<%= form_for @game, :html => {:id => "savegame"} do |f| %>
  <p>
    board
    <%= f.text_field :board %>
  </p>
  <p>
    user_id
    <%= f.text_field :user_id %>
  </p>
  <p>
    won
    <%= f.check_box :won %>
  </p>
  <p>
    winner
    <%= f.text_field :winner %>
  </p>
  <%= f.submit %>
<% end %>

app/views/gamess/add.html.erb
<h1>Gamess#add</h1>
<p>Find me in app/views/gamess/add.html.erb</p>

app/views/gamess/create.html.erb
<h1>Gamess#create</h1>
<p>Find me in app/views/gamess/create.html.erb</p>

app/views/gamess/destroy.html.erb
<h1>Gamess#destroy</h1>
<p>Find me in app/views/gamess/destroy.html.erb</p>

app/views/gamess/edit.html.erb
<h1>Gamess#edit</h1>
<p>Find me in app/views/gamess/edit.html.erb</p>

app/views/gamess/index.html.erb
<h1>Gamess#index</h1>
<p>Find me in app/views/gamess/index.html.erb</p>

app/views/gamess/show.html.erb
<h1>Gamess#show</h1>
<p>Find me in app/views/gamess/show.html.erb</p>

app/views/gamess/update.html.erb
<h1>Gamess#update</h1>
<p>Find me in app/views/gamess/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Tic-Tac-Toe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:controller] %>">
  <!-- If a flash message is provided, display it. -->
  <% if flash[:notice] || flash[:alert] %>
    <div id="flash">
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>Log In</h1>

<h3>Not a user? <%= link_to("Sign up now!", :new_user) %></h3>
<%= form_tag logins_path do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </p>
  
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  
  <%= submit_tag "Log In" %>
<% end %>

app/views/transaction/create.html.erb
<h1>Transaction#create</h1>
<p>Find me in app/views/transaction/create.html.erb</p>

app/views/transaction/destroy.html.erb
<h1>Transaction#destroy</h1>
<p>Find me in app/views/transaction/destroy.html.erb</p>

app/views/transaction/edit.html.erb
<h1>Transaction#edit</h1>
<p>Find me in app/views/transaction/edit.html.erb</p>

app/views/transaction/index.html.erb
<h1>Transaction#index</h1>
<p>Find me in app/views/transaction/index.html.erb</p>

app/views/transaction/new.html.erb
<h1>Transaction#new</h1>
<p>Find me in app/views/transaction/new.html.erb</p>

app/views/transaction/show.html.erb
<h1>Transaction#show</h1>
<p>Find me in app/views/transaction/show.html.erb</p>

app/views/transaction/update.html.erb
<h1>Transaction#update</h1>
<p>Find me in app/views/transaction/update.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error_msg| %>
      <p><%= error_msg %></p>
    <% end %>
  <% end %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :uname %><br />
    <%= f.text_field :uname %>
  </p>
  
  <p>
    <%= f.label :fname, "First Name" %><br />
    <%= f.text_field :fname %>
  </p>
  
  <p>
    <%= f.label :lname, "Last Name" %><br />
    <%= f.text_field :lname %>
  </p>
  
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render :partial => "form" %>

<p>
  <br />
  <%= form_tag(destroy_user_path(@user.id), method: "post") do %>
    <%= submit_tag("Delete Account") %>
  <% end %>
</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= link_to(user.name, user_path(user.id)) %> (<%= user.uname %>)
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= session[:user_id] %> --- <%= params[:id] %></p>

<% if session[:user_id] == params[:id] %>
  <p>
    <%= link_to("Edit User Info", edit_user_path(@user.id)) %>
  </p>
<% end %>